# =============================================================================
#  nix/shell-hook.nix — shellHook string for snifferlauncher dev shell
# =============================================================================
#
#  Returns a bash string that is spliced into mkShell.shellHook.
#  All Nix values are interpolated here; the result is pure bash.
#
{ pkgs, androidSdk, ndkVersion, vscodeExtensions }:

''
  # ── ANSI colour helpers (GitHub Actions palette) ────────────────────────────
  _C_RESET="\033[0m"
  _C_BOLD="\033[1m"
  _C_DIM="\033[2m"

  _C_BLUE="\033[34m"        # group header
  _C_CYAN="\033[36m"        # info / step label
  _C_GREEN="\033[32m"       # success
  _C_YELLOW="\033[33m"      # warning
  _C_RED="\033[31m"         # error
  _C_WHITE="\033[97m"       # value text

  # GitHub-Actions–style helpers
  _gh_group()   { printf "\n''${_C_BOLD}''${_C_BLUE}##[group]%s''${_C_RESET}\n" "$*"; }
  _gh_endgroup(){ printf "''${_C_DIM}##[endgroup]''${_C_RESET}\n"; }
  _gh_step()    { printf "  ''${_C_BOLD}''${_C_CYAN}▶ Run %s''${_C_RESET}\n" "$*"; }
  _gh_ok()      { printf "  ''${_C_GREEN}✓''${_C_RESET}  %s\n" "$*"; }
  _gh_skip()    { printf "  ''${_C_DIM}–  %s''${_C_RESET}\n" "$*"; }
  _gh_warn()    { printf "  ''${_C_YELLOW}⚠  Warning: %s''${_C_RESET}\n" "$*"; }
  _gh_error()   { printf "  ''${_C_RED}✗  Error: %s''${_C_RESET}\n" "$*"; }
  _gh_kv()      { printf "  ''${_C_DIM}%-18s''${_C_RESET} ''${_C_WHITE}%s''${_C_RESET}\n" "$1" "$2"; }

  # ── Banner ──────────────────────────────────────────────────────────────────
  printf "\n''${_C_BOLD}''${_C_BLUE}"
  echo   "╔══════════════════════════════════════════════════════════════════╗"
  echo   "║  🦀  snifferlauncher  ·  Rust × Android × Cross-compilation     ║"
  echo   "║      Nix development shell                                       ║"
  echo   "╚══════════════════════════════════════════════════════════════════╝"
  printf "''${_C_RESET}\n"

  # ── Step 1 — Generate .cargo/config.toml ────────────────────────────────────
  _gh_group "Set up Cargo configuration"
  _gh_step ".cargo/config.toml"
  mkdir -p .cargo
  cat > .cargo/config.toml << 'CARGO_CONFIG'
# Auto-generated by nix/shell-hook.nix — do not edit manually.
# Re-enter nix-shell to regenerate.

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar     = "x86_64-w64-mingw32-ar"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-unknown-linux-musl-gcc"

[target.aarch64-linux-android]
linker = "aarch64-linux-android35-clang"
ar     = "llvm-ar"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi35-clang"
ar     = "llvm-ar"

[target.i686-linux-android]
linker = "i686-linux-android35-clang"
ar     = "llvm-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android35-clang"
ar     = "llvm-ar"
CARGO_CONFIG
  _gh_ok ".cargo/config.toml written"
  _gh_endgroup

  # ── Step 2 — Android environment ────────────────────────────────────────────
  _gh_group "Set up Android SDK / NDK"
  _gh_step "Export ANDROID_HOME, NDK_ROOT, JAVA_HOME"

  export ANDROID_HOME="${androidSdk}/libexec/android-sdk"
  export ANDROID_NDK_ROOT="$ANDROID_HOME/ndk/${ndkVersion}"
  export ANDROID_NDK_HOME="$ANDROID_NDK_ROOT"
  export JAVA_HOME="${pkgs.jdk17}"

  export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
  export PATH="$ANDROID_HOME/platform-tools:$PATH"
  export PATH="$ANDROID_HOME/tools/bin:$PATH"
  export PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
  export PATH="${pkgs.jdk17}/bin:$PATH"

  _gh_kv "ANDROID_HOME"     "$ANDROID_HOME"
  _gh_kv "ANDROID_NDK_ROOT" "$ANDROID_NDK_ROOT"
  _gh_kv "JAVA_HOME"        "$JAVA_HOME"
  _gh_ok "Android environment ready"
  _gh_endgroup

  # ── Step 3 — System library paths ───────────────────────────────────────────
  _gh_group "Set up library paths"
  _gh_step "LD_LIBRARY_PATH / PKG_CONFIG_PATH"

  export LD_LIBRARY_PATH="${pkgs.openssl.out}/lib:${pkgs.zlib.out}/lib:${pkgs.stdenv.cc.cc.lib}/lib:$LD_LIBRARY_PATH"
  export PKG_CONFIG_PATH="${pkgs.openssl.dev}/lib/pkgconfig:${pkgs.zlib.dev}/lib/pkgconfig:$PKG_CONFIG_PATH"

  export OPENSSL_DIR="${pkgs.openssl.dev}"
  export OPENSSL_LIB_DIR="${pkgs.openssl.out}/lib"
  export OPENSSL_INCLUDE_DIR="${pkgs.openssl.dev}/include"

  _gh_ok "OpenSSL, zlib paths exported"
  _gh_endgroup

  # ── Step 4 — Cross-compilation linkers ──────────────────────────────────────
  _gh_group "Set up cross-compilation linkers"
  _gh_step "Windows / musl / Android linker env vars"

  # Windows (MinGW-w64)
  export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="${pkgs.pkgsCross.mingwW64.stdenv.cc}/bin/x86_64-w64-mingw32-gcc"
  export CC_x86_64_pc_windows_gnu="x86_64-w64-mingw32-gcc"
  export CXX_x86_64_pc_windows_gnu="x86_64-w64-mingw32-g++"
  export AR_x86_64_pc_windows_gnu="x86_64-w64-mingw32-ar"

  # Linux musl (static)
  export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="${pkgs.pkgsCross.musl64.stdenv.cc}/bin/x86_64-unknown-linux-musl-gcc"
  export CC_x86_64_unknown_linux_musl="x86_64-unknown-linux-musl-gcc"

  # Android — NDK clang-based linkers (API level 35)
  _NDK_BIN="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin"
  export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$_NDK_BIN/aarch64-linux-android35-clang"
  export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER="$_NDK_BIN/armv7a-linux-androideabi35-clang"
  export CARGO_TARGET_I686_LINUX_ANDROID_LINKER="$_NDK_BIN/i686-linux-android35-clang"
  export CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER="$_NDK_BIN/x86_64-linux-android35-clang"

  export CC_aarch64_linux_android="$_NDK_BIN/aarch64-linux-android35-clang"
  export CXX_aarch64_linux_android="$_NDK_BIN/aarch64-linux-android35-clang++"
  export CC_armv7_linux_androideabi="$_NDK_BIN/armv7a-linux-androideabi35-clang"
  export CXX_armv7_linux_androideabi="$_NDK_BIN/armv7a-linux-androideabi35-clang++"
  export CC_i686_linux_android="$_NDK_BIN/i686-linux-android35-clang"
  export CXX_i686_linux_android="$_NDK_BIN/i686-linux-android35-clang++"
  export CC_x86_64_linux_android="$_NDK_BIN/x86_64-linux-android35-clang"
  export CXX_x86_64_linux_android="$_NDK_BIN/x86_64-linux-android35-clang++"

  _gh_ok "x86_64-pc-windows-gnu  (MinGW-w64)"
  _gh_ok "x86_64-unknown-linux-musl  (static)"
  _gh_ok "aarch64/armv7/i686/x86_64-linux-android  (NDK API 35)"
  _gh_endgroup

  # ── Step 5 — VS Code extensions ─────────────────────────────────────────────
  export VSCODE_EXTENSIONS_DIR="$PWD/.extensions"
  mkdir -p "$VSCODE_EXTENSIONS_DIR"

  # Wrapper to fix LD_LIBRARY_PATH issues when calling the host's VS Code
  function code() {
    env -u LD_LIBRARY_PATH code --extensions-dir "$VSCODE_EXTENSIONS_DIR" "$@"
  }
  export -f code

  _install_vscode_extensions() {
    _gh_group "Install VS Code extensions"

    if ! type -P code &>/dev/null; then
      _gh_warn "'code' not found in PATH — skipping extension installation."
      printf "       Install VS Code or add it to PATH, then re-enter nix-shell.\n"
      _gh_endgroup
      return
    fi

    _gh_step "Syncing extensions → .extensions/"
    local _installed=0 _failed=0 _skipped=0

    while IFS= read -r ext; do
      [[ -z "$ext" ]] && continue

      if env -u LD_LIBRARY_PATH code --extensions-dir "$VSCODE_EXTENSIONS_DIR" --list-extensions 2>/dev/null | grep -qiF "$ext"; then
        _gh_skip "$ext"
        (( _skipped++ )) || true
        continue
      fi

      local _out
      _out=$(env -u LD_LIBRARY_PATH code --extensions-dir "$VSCODE_EXTENSIONS_DIR" --install-extension "$ext" --force 2>&1)
      if [ $? -eq 0 ]; then
        _gh_ok "$ext"
        (( _installed++ )) || true
      else
        _gh_error "$ext"
        echo "$_out" | sed 's/\x1b\[[0-9;]*m//g' | grep -v '^$' | head -2 \
          | sed 's/^/         /'
        (( _failed++ )) || true
      fi
    done << EXTENSIONS
${builtins.concatStringsSep "\n" vscodeExtensions}
EXTENSIONS

    echo ""
    printf "  ''${_C_BOLD}Extensions:''${_C_RESET}  "
    printf "''${_C_GREEN}%d installed''${_C_RESET}  " "$_installed"
    printf "''${_C_DIM}%d skipped''${_C_RESET}  "   "$_skipped"
    [ "$_failed" -gt 0 ] \
      && printf "''${_C_RED}%d failed''${_C_RESET}"  "$_failed" \
      || printf "''${_C_DIM}%d failed''${_C_RESET}"  "$_failed"
    echo ""

    if [ "$_failed" -gt 0 ]; then
      _gh_warn "Some extensions failed. Check internet access or VS Code marketplace login."
      printf "         VSCodium uses open-vsx.org — some extension IDs may differ.\n"
    fi

    _gh_endgroup
  }

  if [ -z "$_SNIFFERLAUNCHER_VSCODE_INSTALLED" ]; then
    export _SNIFFERLAUNCHER_VSCODE_INSTALLED=1
    _install_vscode_extensions
  fi

  # ── Step 6 — Platform-Specific Lints (Clippy) ───────────────────────────────
  export CLIPPY_FLAGS="-D warnings -D clippy::pedantic -D clippy::nursery -D clippy::cargo -A clippy::multiple-crate-versions"
  
  alias lint-linux="cargo clippy --locked --workspace --all-targets --all-features -- \$CLIPPY_FLAGS"
  alias lint-android-aarch64="cargo clippy --target aarch64-linux-android --workspace --all-targets --all-features -- \$CLIPPY_FLAGS"
  alias lint-android-armv7="cargo clippy --target armv7-linux-androideabi --workspace --all-targets --all-features -- \$CLIPPY_FLAGS"
  alias lint-android-x86_64="cargo clippy --target x86_64-linux-android --workspace --all-targets --all-features -- \$CLIPPY_FLAGS"
  alias lint-android-i686="cargo clippy --target i686-linux-android --workspace --all-targets --all-features -- \$CLIPPY_FLAGS"
  alias lint-android="lint-android-aarch64 && lint-android-armv7 && lint-android-x86_64 && lint-android-i686"
  alias lint-macos="cargo clippy --locked --workspace --all-targets --all-features --target aarch64-apple-darwin -- \$CLIPPY_FLAGS"

  # ── Step 7 — Environment summary ────────────────────────────────────────────
  _gh_group "Environment summary"

  _gh_step "Toolchain versions"
  _gh_kv "Rust"   "$(rustc  --version 2>/dev/null || echo 'not found')"
  _gh_kv "Cargo"  "$(cargo  --version 2>/dev/null || echo 'not found')"
  _gh_kv "Java"   "$(java -version 2>&1 | head -1)"
  _gh_kv "NDK"    "$ANDROID_NDK_ROOT"
  _gh_kv "SDK"    "$ANDROID_HOME"

  echo ""
  _gh_step "Available cross-compilation targets"
  _gh_kv "Android"  "cargo build --target aarch64-linux-android"
  _gh_kv "Android"  "cargo build --target armv7-linux-androideabi"
  _gh_kv "Android"  "cargo build --target x86_64-linux-android"
  _gh_kv "Windows"  "cargo build --target x86_64-pc-windows-gnu"
  _gh_kv "Linux"    "cargo build --target x86_64-unknown-linux-musl"

  echo ""
  _gh_step "Quick commands"
  _gh_kv "lint-linux"     "Run strict clippy for Linux"
  _gh_kv "lint-android"   "Run strict clippy for all Android targets"
  _gh_kv "lint-macos"     "Run strict clippy for macOS"
  _gh_kv "fmt"            "cargo fmt --all"
  _gh_kv "test"           "cargo test"

  _gh_endgroup
  echo ""
''
