[package]
name = "sniffer_platform_desktop"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[features]
default = ["devkit"]
devkit = ["sniffer_core/devkit"]

[dependencies]
sniffer_core = { path = "../sniffer_core" }
sniffer_render = { path = "../sniffer_render" }
sniffer_plugin = { path = "../sniffer_plugin" }

winit = "0.30.5"
glutin = "0.32.2"
glutin-winit = "0.5.0"
glow = "0.17.0"
obfstr = "0.4"
image = { version = "0.25.1", default-features = false, features = ["png", "jpeg"] }

[lints]
workspace = true
