filters:
  rust:
    - "src/**"
    - "crates/**"
    - ".plugins/**"
    - "android/**"
    - "Cargo.toml"
    - "Cargo.lock"
    - "deny.toml"
    - ".github/workflows/check.yml"
    - ".github/paths.yaml"
