# bacon.toml - Greenkode Launcher Otomasyonu

default_job = "check"

# Keybindings
[keybindings]
a = "job:android-debug" 
c = "job:android-check"         


# Android debug mode
[jobs.android-debug]
command = [
    "sh",
    "-c",
    "cargo apk build --target x86_64-linux-android --lib && adb -s emulator-5554 install target/debug/apk/snifferlauncher.apk && adb -s emulator-5554 shell am start -W -n com.greenkod.snifferlauncher/android.app.NativeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER --user 0",
]

# Check android project files
[jobs.android-check]
command = [
    "sh",
    "-c",
    "cargo check --target x86_64-linux-android --lib && cargo check --target aarch64-linux-android",
]
need_stdout = true
allow_warnings = true
# run when source code is changed
watch = ["src"]
