# bacon.toml - Greenkode Launcher Otomasyonu

default_job = "check"

# ---- ANA TUŞ ATAMALARI ----
[keybindings]
a = "job:android-yukle" # KESİN EMİR: 'a' tuşuna basınca bu işi tetikle!
c = "job:check"         # 'c' tuşuna basınca sadece check moduna dön

# ---- İŞ TANIMLARI ----

# [c] modu (Sadece hataları tarar)
[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false
watch = ["src"]

# [a] modu (Derler ve Emülatöre Yükler)
[jobs.android-yukle]
command = [
    "sh",
    "-c",
    "cargo apk build --target x86_64-linux-android --lib && adb -s emulator-5554 install target/debug/apk/launcher.apk && adb -s emulator-5554 shell am start -W -n com.greenkod.launcher/android.app.NativeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER --user 0",
]
need_stdout = true
allow_warnings = true
watch = ["src"]
