use std::fs;
use std::path::Path;

/// XOR key used for compile-time shader and JS encryption.
/// Must be kept in sync with `src/secure.rs`.
const XOR_KEY: u8 = 0x5A;

fn xor_encrypt(data: &[u8]) -> Vec<u8> {
    data.iter().map(|b| b ^ XOR_KEY).collect()
}

fn bytes_to_rust_array(bytes: &[u8]) -> String {
    let inner: Vec<String> = bytes.iter().map(|b| format!("0x{b:02X}")).collect();
    format!("&[{}]", inner.join(", "))
}

fn main() {
    // Notify Cargo to rerun build.rs when plugin assets change
    println!("cargo:rerun-if-changed=.plugins");
    println!("cargo:rerun-if-changed=src/plugin/js/ipc_preamble.js");

    // -----------------------------------------------------------------------
    // Dynamic, 100% portable path remapping for any user in any folder on any OS.
    // -----------------------------------------------------------------------
    if let Ok(manifest_dir) = std::env::var("CARGO_MANIFEST_DIR") {
        println!("cargo:rustc-flag=--remap-path-prefix={manifest_dir}=/src");
        let fwd_manifest = manifest_dir.replace('\\', "/");
        if fwd_manifest != manifest_dir {
            println!("cargo:rustc-flag=--remap-path-prefix={fwd_manifest}=/src");
        }
    }

    if let Ok(home) = std::env::var("USERPROFILE").or_else(|_| std::env::var("HOME")) {
        // Remap rustup toolchains directory FIRST (prevents toolchain name leaks)
        let rustup_tc = format!("{home}\\.rustup\\toolchains");
        println!("cargo:rustc-flag=--remap-path-prefix={rustup_tc}=/rust");
        let fwd_rustup_tc = rustup_tc.replace('\\', "/");
        println!("cargo:rustc-flag=--remap-path-prefix={fwd_rustup_tc}=/rust");

        let rustup = format!("{home}\\.rustup");
        println!("cargo:rustc-flag=--remap-path-prefix={rustup}=/rust");
        let fwd_rustup = rustup.replace('\\', "/");
        println!("cargo:rustc-flag=--remap-path-prefix={fwd_rustup}=/rust");

        let cargo_dir = format!("{home}\\.cargo");
        println!("cargo:rustc-flag=--remap-path-prefix={cargo_dir}=/cargo");
        let fwd_cargo = cargo_dir.replace('\\', "/");
        println!("cargo:rustc-flag=--remap-path-prefix={fwd_cargo}=/cargo");

        // Remap home directory LAST
        println!("cargo:rustc-flag=--remap-path-prefix={home}=/anon");
        let fwd_home = home.replace('\\', "/");
        if fwd_home != home {
            println!("cargo:rustc-flag=--remap-path-prefix={fwd_home}=/anon");
        }
    }

    let shader_dir = "src/core/render/shaders";
    let shader_files: &[(&str, &str)] = &[
        ("shape_android.vs",  "SHAPE_ANDROID_VS"),
        ("shape_android.fs",  "SHAPE_ANDROID_FS"),
        ("text_android.vs",   "TEXT_ANDROID_VS"),
        ("text_android.fs",   "TEXT_ANDROID_FS"),
        ("image_android.vs",  "IMAGE_ANDROID_VS"),
        ("image_android.fs",  "IMAGE_ANDROID_FS"),
        ("shape_desktop.vs",  "SHAPE_DESKTOP_VS"),
        ("shape_desktop.fs",  "SHAPE_DESKTOP_FS"),
        ("text_desktop.vs",   "TEXT_DESKTOP_VS"),
        ("text_desktop.fs",   "TEXT_DESKTOP_FS"),
        ("image_desktop.vs",  "IMAGE_DESKTOP_VS"),
        ("image_desktop.fs",  "IMAGE_DESKTOP_FS"),
    ];

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("encrypted_assets.rs");

    let mut output = String::from(
        "// Auto-generated by build.rs — DO NOT EDIT.\n\
         // All byte arrays are XOR-encrypted; use `crate::secure::decrypt()` at runtime.\n\n",
    );

    // Encrypt each shader file
    for (file, const_name) in shader_files {
        let src_path = format!("{shader_dir}/{file}");
        println!("cargo:rerun-if-changed={src_path}");

        let raw = match fs::read(&src_path) {
            Ok(b) => b,
            Err(e) => {
                eprintln!("cargo:warning=build.rs: cannot read {src_path}: {e}");
                continue;
            }
        };

        let enc = xor_encrypt(&raw);
        output.push_str(&format!(
            "#[allow(dead_code)]\npub static {const_name}: &[u8] = {};\n\n",
            bytes_to_rust_array(&enc)
        ));
    }

    // Encrypt the JS IPC preamble
    let preamble_path = "src/plugin/js/ipc_preamble.js";
    println!("cargo:rerun-if-changed={preamble_path}");

    let preamble_raw = match fs::read(preamble_path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("cargo:warning=build.rs: cannot read {preamble_path}: {e}");
            vec![]
        }
    };

    let preamble_enc = xor_encrypt(&preamble_raw);
    output.push_str(&format!(
        "#[allow(dead_code)]\npub static IPC_PREAMBLE_JS: &[u8] = {};\n",
        bytes_to_rust_array(&preamble_enc)
    ));

    fs::write(&out_path, &output).expect("build.rs: failed to write encrypted_assets.rs");

    // Copy .plugins directory to build profile output directory (target/debug/.plugins or target/release/.plugins)
    let out_dir_path = Path::new(&out_dir);
    if let Some(profile_dir) = out_dir_path.ancestors().nth(3) {
        let target_plugins = profile_dir.join(".plugins");
        let src_plugins = Path::new(".plugins");
        if src_plugins.exists() {
            let _ = copy_dir_all(src_plugins, &target_plugins);
        }
    }
}

fn copy_dir_all(src: impl AsRef<Path>, dst: impl AsRef<Path>) -> std::io::Result<()> {
    let dst_path = dst.as_ref();
    fs::create_dir_all(dst_path)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let dest_entry = dst_path.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(entry.path(), &dest_entry)?;
        } else {
            let _ = fs::copy(entry.path(), &dest_entry);
        }
    }
    Ok(())
}
