[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unlicense",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
]

[[licenses.clarify]]
name = "snifferlauncher"
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0x0 }
]

[licenses.private]
ignore = false