#![allow(clippy::pedantic, clippy::nursery)]

pub mod engine;
pub mod host_api;
pub mod permission_manager;

use crate::core::types::Element;
use crate::core::ui::data_map::DataMap;
use crate::core::ui::event::UiEvent;
use crate::core::ui::style_map::StyleMap;
use crate::core::ui::widget::WidgetId;
use crate::plugin::registry::{ApiMap, BroadcastQueue};
use crate::plugin::r#trait::UiPlugin;
use rquickjs::{Context, Runtime, Value};
use std::sync::{Arc, Mutex};

use obfstr::obfstr;
use engine::create_engine;
use host_api::{HostApiConfig, register_host_api};

// ---------------------------------------------------------------------------
// Encrypted JS preamble — generated by build.rs at compile time.
// Decrypted ephemerally at runtime, never stored as a static &str.
// ---------------------------------------------------------------------------
mod encrypted_assets {
    include!(concat!(env!("OUT_DIR"), "/encrypted_assets.rs"));
}

// ---------------------------------------------------------------------------
// JsPlugin
// ---------------------------------------------------------------------------

#[allow(dead_code)]
pub struct JsPlugin {
    script_content: String,
    runtime: Runtime,
    context: Context,
    subscriptions: Vec<WidgetId>,
    ui_tree: Arc<Mutex<Option<Element>>>,
    gc_counter: std::sync::Mutex<u32>,
    action_queue: Arc<Mutex<Vec<crate::core::types::Action>>>,
    api_map: ApiMap,
    broadcast_queue: BroadcastQueue,
    permissions: Vec<String>,
    granted_permissions: Arc<Mutex<Vec<String>>>,
}

#[allow(clippy::non_send_fields_in_send_ty)]
unsafe impl Send for JsPlugin {}
unsafe impl Sync for JsPlugin {}

pub struct JsPluginConfig {
    pub script_content: String,
    pub plugin_id: String,
    pub action_queue: Arc<Mutex<Vec<crate::core::types::Action>>>,
    pub api_map: ApiMap,
    pub broadcast_queue: BroadcastQueue,
    pub permissions: Vec<String>,
    pub default_settings: serde_json::Value,
    pub cached_ui: Option<Element>,
    pub cache_path: Option<std::path::PathBuf>,
}

struct JsPluginEnvConfig {
    pub plugin_id: String,
    pub ui_tree: Arc<Mutex<Option<Element>>>,
    pub action_queue: Arc<Mutex<Vec<crate::core::types::Action>>>,
    pub api_map: ApiMap,
    pub broadcast_queue: BroadcastQueue,
    pub plugin_permissions: Vec<String>,
    pub granted_permissions: Arc<Mutex<Vec<String>>>,
    pub default_settings: serde_json::Value,
    pub cache_path: Option<std::path::PathBuf>,
}

impl JsPlugin {
    /// Initialize a QuickJS runtime and context for a plugin.
    ///
    /// # Errors
    /// Returns a `String` error if runtime/context creation or script evaluation fails.
    pub fn new(config: JsPluginConfig) -> Result<Self, String> {
        let (runtime, context) = create_engine()?;
        let ui_tree = Arc::new(Mutex::new(config.cached_ui));

        #[cfg(not(target_os = "android"))]
        let initial_granted = config.permissions.clone();

        #[cfg(target_os = "android")]
        let initial_granted: Vec<String> = config
            .permissions
            .iter()
            .filter(|p| p.starts_with("plugin.permission.") || p.starts_with("android.permission."))
            .cloned()
            .collect();

        let granted_permissions = Arc::new(Mutex::new(initial_granted));
        let permissions_clone = config.permissions.clone();

        let plugin = Self {
            script_content: config.script_content,
            runtime,
            context,
            subscriptions: vec![],
            ui_tree: ui_tree.clone(),
            gc_counter: std::sync::Mutex::new(0),
            action_queue: config.action_queue.clone(),
            api_map: config.api_map.clone(),
            broadcast_queue: config.broadcast_queue.clone(),
            permissions: config.permissions.clone(),
            granted_permissions: granted_permissions.clone(),
        };

        plugin.init_js_env(JsPluginEnvConfig {
            plugin_id: config.plugin_id,
            ui_tree,
            action_queue: config.action_queue,
            api_map: config.api_map,
            broadcast_queue: config.broadcast_queue,
            plugin_permissions: permissions_clone,
            granted_permissions: granted_permissions.clone(),
            default_settings: config.default_settings,
            cache_path: config.cache_path,
        })?;

        Ok(plugin)
    }

    fn init_js_env(&self, config: JsPluginEnvConfig) -> Result<(), String> {
        // Clone the context to pass into host_api (captured as SafeContext).
        let context_clone = self.context.clone();

        self.context.with(|ctx| {
            register_host_api(
                &ctx,
                HostApiConfig {
                    plugin_id: config.plugin_id,
                    context: context_clone,
                    ui_tree: config.ui_tree,
                    action_queue: config.action_queue,
                    api_map: config.api_map,
                    broadcast_queue: config.broadcast_queue,
                    plugin_permissions: config.plugin_permissions,
                    granted_permissions: config.granted_permissions,
                    default_settings: config.default_settings,
                    cache_path: config.cache_path,
                },
            );

            // Inject the IPC preamble before the plugin's own code.
            // Decrypt the preamble at runtime — it is dropped after eval() returns.
            let ipc_preamble = crate::secure::decrypt(encrypted_assets::IPC_PREAMBLE_JS);
            let _ = ctx
                .eval::<Value, _>(ipc_preamble.as_bytes())
                .map_err(|e| e.to_string())?;

            // Evaluate the plugin script.
            let _ = ctx
                .eval::<Value, _>(self.script_content.as_bytes())
                .map_err(|e| e.to_string())?;

            Ok::<(), String>(())
        })?;

        Ok(())
    }
}

impl UiPlugin for JsPlugin {
    fn subscriptions(&self) -> &[WidgetId] {
        &[]
    }

    fn build_ui(&self) -> Option<Element> {
        if let Ok(lock) = self.ui_tree.lock() {
            return lock.clone();
        }
        None
    }

    fn on_event(
        &self,
        event: &UiEvent,
        _styles: &StyleMap,
        _data: &DataMap,
        _actions: &Arc<Mutex<Vec<crate::core::types::Action>>>,
    ) {
        self.context.with(|ctx| {
            let globals = ctx.globals();
            if let Ok(on_event_fn) = globals.get::<_, rquickjs::Function>("onEvent") {
                let event_json = match event {
                    UiEvent::Click(id, w, h) => {
                        format!("{{\"{}\":\"{}\",\"{}\":\"{id}\",\"{}\":{w},\"{}\":{h}}}", obfstr!("type"), obfstr!("Click"), obfstr!("id"), obfstr!("w"), obfstr!("h"))
                    }
                    UiEvent::Hover(id, w, h, x, y) => {
                        format!("{{\"{}\":\"{}\",\"{}\":\"{id}\",\"{}\":{w},\"{}\":{h},\"{}\":{x},\"{}\":{y}}}", obfstr!("type"), obfstr!("Hover"), obfstr!("id"), obfstr!("w"), obfstr!("h"), obfstr!("x"), obfstr!("y"))
                    }
                    UiEvent::HoverEnd(id) => {
                        format!("{{\"{}\":\"{}\",\"{}\":\"{id}\"}}", obfstr!("type"), obfstr!("HoverEnd"), obfstr!("id"))
                    }
                    UiEvent::TextInput(text) => format!(
                        "{{\"{}\":\"{}\",\"{}\":{}}}",
                        obfstr!("type"),
                        obfstr!("TextInput"),
                        obfstr!("text"),
                        serde_json::to_string(text).unwrap_or_default()
                    ),
                    UiEvent::ClickOutside => format!("{{\"{}\":\"{}\"}}", obfstr!("type"), obfstr!("ClickOutside")),
                    UiEvent::Backspace => format!("{{\"{}\":\"{}\"}}", obfstr!("type"), obfstr!("Backspace")),
                    UiEvent::PointerDown(id) => format!("{{\"{}\":\"{}\",\"{}\":\"{id}\"}}", obfstr!("type"), obfstr!("PointerDown"), obfstr!("id")),
                    UiEvent::PointerUp(id_opt) => {
                        let id_str = match id_opt {
                            Some(id) => format!("\"{id}\""),
                            None => obfstr!("null").to_string(),
                        };
                        format!("{{\"{}\":\"{}\",\"{}\":{id_str}}}", obfstr!("type"), obfstr!("PointerUp"), obfstr!("id"))
                    }
                    UiEvent::Scroll(id_opt, dx, dy, max_x, max_y) => {
                        let id_str = match id_opt {
                            Some(id) => format!("\"{id}\""),
                            None => obfstr!("null").to_string(),
                        };
                        format!(
                            "{{\"{}\":\"{}\",\"{}\":{id_str},\"{}\":{dx},\"{}\":{dy},\"{}\":{max_x},\"{}\":{max_y}}}",
                            obfstr!("type"), obfstr!("Scroll"), obfstr!("id"), obfstr!("dx"), obfstr!("dy"), obfstr!("max_x"), obfstr!("max_y")
                        )
                    }
                    UiEvent::WindowResized(w, h) => {
                        format!("{{\"{}\":\"{}\",\"{}\":{w},\"{}\":{h}}}", obfstr!("type"), obfstr!("WindowResized"), obfstr!("w"), obfstr!("h"))
                    }
                    UiEvent::PageSnapped { widget_id, page } => {
                        format!(
                            "{{\"{}\":\"{}\",\"{}\":{widget_id},\"{}\":{page}}}",
                            obfstr!("type"), obfstr!("PageSnapped"),
                            obfstr!("widget_id"),
                            obfstr!("page")
                        )
                    }
                };

                let res: Result<String, _> = on_event_fn.call((event_json,));
                if let Ok(_cmds_json) = res {
                    // Expect JS to return an array of DrawCommands or Actions in JSON
                }
            }
        });
    }

    fn on_tick(&self) {
        if let Ok(mut count) = self.gc_counter.lock() {
            *count += 1;
            if *count >= 300 {
                *count = 0;
                self.runtime.run_gc();
            }
        }

        self.context.with(|ctx| {
            if let Ok(handler) = ctx.globals().get::<_, rquickjs::Function>("_onTimerTick") {
                let _ = handler.call::<_, ()>(());
            }
        });
    }

    /// Deliver a broadcast from another plugin to this plugin's `onBroadcast` handler.
    fn on_broadcast(&self, channel: &str, payload_json: &str) {
        self.context.with(|ctx| {
            if let Ok(handler) = ctx
                .globals()
                .get::<_, rquickjs::Function>("_dispatchBroadcast")
            {
                let _ = handler.call::<_, ()>((channel.to_string(), payload_json.to_string()));
            }
        });
    }
}
