use std::fs;
use std::path::Path;

const XOR_KEY: u8 = 0x5A;

fn xor_encrypt(data: &[u8]) -> Vec<u8> {
    data.iter().map(|b| b ^ XOR_KEY).collect()
}

fn bytes_to_rust_array(bytes: &[u8]) -> String {
    let inner: Vec<String> = bytes.iter().map(|b| format!("0x{b:02X}")).collect();
    format!("&[{}]", inner.join(", "))
}

fn main() {
    let preamble_path = "src/js/ipc_preamble.js";
    println!("cargo:rerun-if-changed={preamble_path}");

    let preamble_raw = match fs::read(preamble_path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("cargo:warning=build.rs: cannot read {preamble_path}: {e}");
            vec![]
        }
    };

    let preamble_enc = xor_encrypt(&preamble_raw);
    let mut output = String::from(
        "// Auto-generated by build.rs — DO NOT EDIT.\n\
         // All byte arrays are XOR-encrypted; use `crate::secure::decrypt()` at runtime.\n\n",
    );
    use std::fmt::Write as _;
    let _ = write!(
        output,
        "#[allow(dead_code)]\npub static IPC_PREAMBLE_JS: &[u8] = {};\n",
        bytes_to_rust_array(&preamble_enc)
    );

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("encrypted_assets.rs");
    fs::write(&out_path, &output).expect("build.rs: failed to write encrypted_assets.rs");
}
