use std::fs;
use std::path::Path;

fn main() {
    let shader_dir = "src/shaders";
    let shader_files: &[(&str, &str)] = &[
        ("shape_android.vs", "SHAPE_ANDROID_VS"),
        ("shape_android.fs", "SHAPE_ANDROID_FS"),
        ("text_android.vs", "TEXT_ANDROID_VS"),
        ("text_android.fs", "TEXT_ANDROID_FS"),
        ("image_android.vs", "IMAGE_ANDROID_VS"),
        ("image_android.fs", "IMAGE_ANDROID_FS"),
        ("shape_desktop.vs", "SHAPE_DESKTOP_VS"),
        ("shape_desktop.fs", "SHAPE_DESKTOP_FS"),
        ("text_desktop.vs", "TEXT_DESKTOP_VS"),
        ("text_desktop.fs", "TEXT_DESKTOP_FS"),
        ("image_desktop.vs", "IMAGE_DESKTOP_VS"),
        ("image_desktop.fs", "IMAGE_DESKTOP_FS"),
    ];

    // Resolve the absolute path to the shader directory so include_str! macros
    // in the generated file resolve correctly regardless of OUT_DIR location.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let shader_abs = Path::new(&manifest_dir).join(shader_dir);

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("shader_assets.rs");

    let mut output = String::from("// Auto-generated by build.rs — DO NOT EDIT.\n\n");

    for (file, const_name) in shader_files {
        let src_path = format!("{shader_dir}/{file}");
        println!("cargo:rerun-if-changed={src_path}");

        let abs = shader_abs.join(file);
        if !abs.exists() {
            eprintln!(
                "cargo:warning=build.rs: shader not found: {}",
                abs.display()
            );
            continue;
        }

        use std::fmt::Write as _;
        let _ = writeln!(
            output,
            "#[allow(dead_code)]\npub static {const_name}: &str = include_str!(r\"{}\");\n",
            abs.display()
        );

        // Validate the file is valid UTF-8 at build time; fail fast if not.
        match fs::read_to_string(&abs) {
            Ok(_) => {}
            Err(e) => {
                panic!("build.rs: shader {file} is not valid UTF-8: {e}");
            }
        }
    }

    fs::write(&out_path, &output).expect("build.rs: failed to write shader_assets.rs");
}
