use std::fs;
use std::path::Path;

const XOR_KEY: u8 = 0x5A;

fn xor_encrypt(data: &[u8]) -> Vec<u8> {
    data.iter().map(|b| b ^ XOR_KEY).collect()
}

fn bytes_to_rust_array(bytes: &[u8]) -> String {
    let inner: Vec<String> = bytes.iter().map(|b| format!("0x{b:02X}")).collect();
    format!("&[{}]", inner.join(", "))
}

fn main() {
    let shader_dir = "src/shaders";
    let shader_files: &[(&str, &str)] = &[
        ("shape_android.vs", "SHAPE_ANDROID_VS"),
        ("shape_android.fs", "SHAPE_ANDROID_FS"),
        ("text_android.vs", "TEXT_ANDROID_VS"),
        ("text_android.fs", "TEXT_ANDROID_FS"),
        ("image_android.vs", "IMAGE_ANDROID_VS"),
        ("image_android.fs", "IMAGE_ANDROID_FS"),
        ("shape_desktop.vs", "SHAPE_DESKTOP_VS"),
        ("shape_desktop.fs", "SHAPE_DESKTOP_FS"),
        ("text_desktop.vs", "TEXT_DESKTOP_VS"),
        ("text_desktop.fs", "TEXT_DESKTOP_FS"),
        ("image_desktop.vs", "IMAGE_DESKTOP_VS"),
        ("image_desktop.fs", "IMAGE_DESKTOP_FS"),
    ];

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("encrypted_assets.rs");

    let mut output = String::from(
        "// Auto-generated by build.rs — DO NOT EDIT.\n\
         // All byte arrays are XOR-encrypted; use `crate::secure::decrypt()` at runtime.\n\n",
    );

    for (file, const_name) in shader_files {
        let src_path = format!("{shader_dir}/{file}");
        println!("cargo:rerun-if-changed={src_path}");

        let raw = match fs::read(&src_path) {
            Ok(b) => b,
            Err(e) => {
                eprintln!("cargo:warning=build.rs: cannot read {src_path}: {e}");
                continue;
            }
        };

        let enc = xor_encrypt(&raw);
        use std::fmt::Write as _;
        let _ = write!(
            output,
            "#[allow(dead_code)]\npub static {const_name}: &[u8] = {};\n\n",
            bytes_to_rust_array(&enc)
        );
    }

    fs::write(&out_path, &output).expect("build.rs: failed to write encrypted_assets.rs");
}
