[package]
name = "sniffer_render"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[features]
default = []
devkit = ["sniffer_core/devkit"]

[dependencies]
sniffer_core = { path = "../sniffer_core" }
glow = "0.17.0"
swash = { version = "0.2.9", features = ["scale"] }
image = { version = "0.25.1", default-features = false, features = ["png", "jpeg"] }
obfstr = "0.4"

[lints]
workspace = true
