use crate::core::render::api::Renderer;
use crate::core::render::math::geometry::Rect;

use crate::core::render::text::font_atlas::{self, FontAtlas};
use crate::dev_err;
use glow::HasContext;
use obfstr::obfstr;

pub mod shaders;
pub mod text;

pub struct GlowRenderer {
    pub(crate) gl: glow::Context,
    pub(crate) quad_vertex_array: glow::VertexArray,
    pub(crate) _quad_vertex_buffer: glow::Buffer,
    pub(crate) shape_program: glow::Program,
    pub(crate) text_program: glow::Program,
    pub(crate) font_texture: glow::Texture,
    pub(crate) resolution: (f32, f32),
    pub(crate) font_atlas: Option<FontAtlas>,
    pub(crate) atlas_width: i32,
    pub(crate) atlas_height: i32,
    pub(crate) image_program: glow::Program,
    pub(crate) image_textures: std::collections::HashMap<String, (glow::Texture, f32, f32)>,
    pub(crate) global_alpha: f32,
    pub(crate) transform_stack: Vec<[f32; 9]>,
    pub(crate) clip_stack: Vec<(Rect, f32)>,
}

fn unpack_color(color: u32) -> [f32; 4] {
    let a =
        f32::from(u8::try_from((color >> 24) & 0xff).expect("alpha channel fits in u8")) / 255.0;
    let r = f32::from(u8::try_from((color >> 16) & 0xff).expect("red channel fits in u8")) / 255.0;
    let g = f32::from(u8::try_from((color >> 8) & 0xff).expect("green channel fits in u8")) / 255.0;
    let b = f32::from(u8::try_from(color & 0xff).expect("blue channel fits in u8")) / 255.0;
    // Default alpha to 1.0 if not specified (i.e. color is 0xRRGGBB)
    let a = if a == 0.0 && color != 0 { 1.0 } else { a };
    [r, g, b, a]
}

#[allow(clippy::cast_possible_truncation)]
fn f32_to_i32(value: f32) -> i32 {
    value as i32
}

impl GlowRenderer {
    #![allow(clippy::missing_safety_doc)]
    /// Create a renderer using the built-in bitmap font.
    ///
    /// # Errors
    ///
    /// Returns an error if GL object creation, shader compilation, or program linking fails.
    pub unsafe fn new(gl: glow::Context) -> Result<Self, String> {
        unsafe { Self::with_font(gl, None) }
    }

    /// Create a renderer using optional TTF font bytes.
    ///
    /// # Errors
    ///
    /// Returns an error if GL object creation, shader compilation, or program linking fails.
    pub unsafe fn with_font(gl: glow::Context, font_data: Option<&[u8]>) -> Result<Self, String> {
        unsafe {
            // Vertex coordinates of a simple unit quad (2 triangles)
            let quad_vertices: [f32; 8] = [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0];

            // 1. Create Quad VAO & VBO
            let quad_vertex_array = gl.create_vertex_array()?;
            gl.bind_vertex_array(Some(quad_vertex_array));
            let quad_vertex_buffer = gl.create_buffer()?;
            gl.bind_buffer(glow::ARRAY_BUFFER, Some(quad_vertex_buffer));
            let quad_bytes = std::slice::from_raw_parts(
                quad_vertices.as_ptr().cast::<u8>(),
                std::mem::size_of_val(&quad_vertices),
            );
            gl.buffer_data_u8_slice(glow::ARRAY_BUFFER, quad_bytes, glow::STATIC_DRAW);
            gl.enable_vertex_attrib_array(0);
            gl.vertex_attrib_pointer_f32(0, 2, glow::FLOAT, false, 8, 0);

            // Encrypted shader assets generated by build.rs at compile time.
            // Each static is a XOR-encrypted byte array; decrypted ephemerally at runtime.
            mod enc {
                include!(concat!(env!("OUT_DIR"), "/encrypted_assets.rs"));
            }

            // 2. Compile shaders based on target OS — decrypted to temporary Strings
            #[cfg(target_os = "android")]
            let (
                shape_vertex_src,
                shape_fragment_src,
                text_vertex_src,
                text_fragment_src,
                image_vertex_src,
                image_fragment_src,
            ) = (
                crate::secure::decrypt(enc::SHAPE_ANDROID_VS),
                crate::secure::decrypt(enc::SHAPE_ANDROID_FS),
                crate::secure::decrypt(enc::TEXT_ANDROID_VS),
                crate::secure::decrypt(enc::TEXT_ANDROID_FS),
                crate::secure::decrypt(enc::IMAGE_ANDROID_VS),
                crate::secure::decrypt(enc::IMAGE_ANDROID_FS),
            );

            #[cfg(not(target_os = "android"))]
            let (
                shape_vertex_src,
                shape_fragment_src,
                text_vertex_src,
                text_fragment_src,
                image_vertex_src,
                image_fragment_src,
            ) = (
                crate::secure::decrypt(enc::SHAPE_DESKTOP_VS),
                crate::secure::decrypt(enc::SHAPE_DESKTOP_FS),
                crate::secure::decrypt(enc::TEXT_DESKTOP_VS),
                crate::secure::decrypt(enc::TEXT_DESKTOP_FS),
                crate::secure::decrypt(enc::IMAGE_DESKTOP_VS),
                crate::secure::decrypt(enc::IMAGE_DESKTOP_FS),
            );

            let shape_program =
                shaders::compile_program(&gl, shape_vertex_src.as_str(), shape_fragment_src.as_str())?;
            let text_program = shaders::compile_program(&gl, text_vertex_src.as_str(), text_fragment_src.as_str())?;
            let image_program =
                shaders::compile_program(&gl, image_vertex_src.as_str(), image_fragment_src.as_str())?;

            // 3. Create font atlas texture
            let (font_texture, font_atlas, atlas_width, atlas_height) =
                if let Some(font_bytes) = font_data {
                    if let Ok(atlas) = font_atlas::build_font_atlas(&gl, font_bytes, 64.0) {
                        dev_err!(
                            "{} ({}x{})",
                            obfstr!("[DEBUG] Using TTF font atlas"),
                            atlas.atlas_width, atlas.atlas_height
                        );
                        let tex = atlas.texture;
                        let w = atlas.atlas_width;
                        let h = atlas.atlas_height;
                        (tex, Some(atlas), w, h)
                    } else {
                        dev_err!("{}", obfstr!("[DEBUG] TTF build failed, falling back to bitmap"));
                        text::create_bitmap_font_atlas(&gl)?
                    }
                } else {
                    dev_err!("{}", obfstr!("[DEBUG] No font data, using bitmap fallback"));
                    text::create_bitmap_font_atlas(&gl)?
                };

            // Enable alpha blending
            gl.enable(glow::BLEND);
            gl.blend_func(glow::SRC_ALPHA, glow::ONE_MINUS_SRC_ALPHA);

            Ok(Self {
                gl,
                quad_vertex_array,
                _quad_vertex_buffer: quad_vertex_buffer,
                shape_program,
                text_program,
                font_texture,
                resolution: (800.0, 600.0),
                font_atlas,
                atlas_width,
                atlas_height,
                image_program,
                image_textures: std::collections::HashMap::new(),
                global_alpha: 1.0,
                transform_stack: vec![[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]],
                clip_stack: Vec::new(),
            })
        }
    }
}

impl Renderer for GlowRenderer {
    fn clear(&mut self, color: u32) {
        let col = unpack_color(color);
        unsafe {
            self.gl.clear_color(col[0], col[1], col[2], col[3]);
            self.gl.clear(glow::COLOR_BUFFER_BIT);
        }
    }

    fn draw_rect(
        &mut self,
        rect: Rect,
        color: u32,
        radius: f32,
        border_width: f32,
        border_color: Option<u32>,
    ) {
        self.draw_rect_gradient(rect, color, color, radius, border_width, border_color);
    }

    fn draw_rect_gradient(
        &mut self,
        rect: Rect,
        color_top: u32,
        color_bottom: u32,
        radius: f32,
        border_width: f32,
        border_color: Option<u32>,
    ) {
        let mut col_top = unpack_color(color_top);
        let mut col_bot = unpack_color(color_bottom);
        col_top[3] *= self.global_alpha;
        col_bot[3] *= self.global_alpha;

        let mut b_col = unpack_color(border_color.unwrap_or(0));
        b_col[3] *= self.global_alpha;

        let is_gradient = if color_top == color_bottom {
            0.0f32
        } else {
            1.0f32
        };

        unsafe {
            self.gl.use_program(Some(self.shape_program));
            self.gl.bind_vertex_array(Some(self.quad_vertex_array));

            // Set uniforms
            let loc_res = self
                .gl
                .get_uniform_location(self.shape_program, "u_resolution");
            let loc_rect_pos = self
                .gl
                .get_uniform_location(self.shape_program, "u_rect_pos");
            let loc_rect_size = self
                .gl
                .get_uniform_location(self.shape_program, "u_rect_size");
            let loc_color = self.gl.get_uniform_location(self.shape_program, "u_color");
            let loc_radius = self.gl.get_uniform_location(self.shape_program, "u_radius");
            let loc_border_w = self
                .gl
                .get_uniform_location(self.shape_program, "u_border_width");
            let loc_border_col = self
                .gl
                .get_uniform_location(self.shape_program, "u_border_color");
            let loc_is_circle = self
                .gl
                .get_uniform_location(self.shape_program, "u_is_circle");
            let loc_is_shadow = self
                .gl
                .get_uniform_location(self.shape_program, "u_is_shadow");
            let loc_is_gradient = self
                .gl
                .get_uniform_location(self.shape_program, "u_is_gradient");
            let loc_color_bot = self
                .gl
                .get_uniform_location(self.shape_program, "u_color_bottom");
            let loc_shape_size = self
                .gl
                .get_uniform_location(self.shape_program, "u_shape_size");

            self.gl
                .uniform_2_f32(loc_res.as_ref(), self.resolution.0, self.resolution.1);
            self.gl.uniform_2_f32(loc_rect_pos.as_ref(), rect.x, rect.y);
            self.gl
                .uniform_2_f32(loc_rect_size.as_ref(), rect.width, rect.height);
            self.gl
                .uniform_2_f32(loc_shape_size.as_ref(), rect.width, rect.height);
            self.gl.uniform_4_f32(
                loc_color.as_ref(),
                col_top[0],
                col_top[1],
                col_top[2],
                col_top[3],
            );
            self.gl.uniform_1_f32(loc_radius.as_ref(), radius);
            self.gl.uniform_1_f32(loc_border_w.as_ref(), border_width);
            self.gl.uniform_4_f32(
                loc_border_col.as_ref(),
                b_col[0],
                b_col[1],
                b_col[2],
                b_col[3],
            );
            self.gl.uniform_1_f32(loc_is_circle.as_ref(), 0.0);
            self.gl.uniform_1_f32(loc_is_shadow.as_ref(), 0.0);
            self.gl.uniform_1_f32(loc_is_gradient.as_ref(), is_gradient);
            self.gl.uniform_4_f32(
                loc_color_bot.as_ref(),
                col_bot[0],
                col_bot[1],
                col_bot[2],
                col_bot[3],
            );

            let loc_transform = self
                .gl
                .get_uniform_location(self.shape_program, "u_transform");
            let t = self.transform_stack.last().unwrap();
            self.gl
                .uniform_matrix_3_f32_slice(loc_transform.as_ref(), false, t);
            self.gl.draw_arrays(glow::TRIANGLE_STRIP, 0, 4);
        }
    }

    fn draw_shadow(&mut self, rect: Rect, radius: f32, offset_y: f32, spread: f32, color: u32) {
        let mut col = unpack_color(color);
        col[3] *= self.global_alpha;
        unsafe {
            self.gl.use_program(Some(self.shape_program));
            self.gl.bind_vertex_array(Some(self.quad_vertex_array));

            let loc_res = self
                .gl
                .get_uniform_location(self.shape_program, "u_resolution");
            let loc_rect_pos = self
                .gl
                .get_uniform_location(self.shape_program, "u_rect_pos");
            let loc_rect_size = self
                .gl
                .get_uniform_location(self.shape_program, "u_rect_size");
            let loc_color = self.gl.get_uniform_location(self.shape_program, "u_color");
            let loc_radius = self.gl.get_uniform_location(self.shape_program, "u_radius");
            let loc_is_circle = self
                .gl
                .get_uniform_location(self.shape_program, "u_is_circle");
            let loc_is_shadow = self
                .gl
                .get_uniform_location(self.shape_program, "u_is_shadow");
            let loc_shadow_blur = self
                .gl
                .get_uniform_location(self.shape_program, "u_shadow_blur");
            let loc_shape_size = self
                .gl
                .get_uniform_location(self.shape_program, "u_shape_size");

            let blur = spread * 1.5;
            let padding = blur * 2.0; // Extend quad to fit the blurred shadow

            let shadow_rect = Rect {
                x: rect.x - spread - padding,
                y: rect.y + offset_y - spread - padding,
                width: spread.mul_add(2.0, rect.width) + padding * 2.0,
                height: spread.mul_add(2.0, rect.height) + padding * 2.0,
            };

            let shape_size_x = spread.mul_add(2.0, rect.width);
            let shape_size_y = spread.mul_add(2.0, rect.height);

            self.gl
                .uniform_2_f32(loc_res.as_ref(), self.resolution.0, self.resolution.1);
            self.gl
                .uniform_2_f32(loc_rect_pos.as_ref(), shadow_rect.x, shadow_rect.y);
            self.gl.uniform_2_f32(
                loc_rect_size.as_ref(),
                shadow_rect.width,
                shadow_rect.height,
            );
            self.gl
                .uniform_2_f32(loc_shape_size.as_ref(), shape_size_x, shape_size_y);
            self.gl
                .uniform_4_f32(loc_color.as_ref(), col[0], col[1], col[2], col[3]);
            self.gl.uniform_1_f32(loc_radius.as_ref(), radius + spread);
            self.gl.uniform_1_f32(loc_is_circle.as_ref(), 0.0);
            self.gl.uniform_1_f32(loc_is_shadow.as_ref(), 1.0);
            self.gl.uniform_1_f32(loc_shadow_blur.as_ref(), blur);

            let loc_transform = self
                .gl
                .get_uniform_location(self.shape_program, "u_transform");
            let t = self.transform_stack.last().unwrap();
            self.gl
                .uniform_matrix_3_f32_slice(loc_transform.as_ref(), false, t);
            self.gl.draw_arrays(glow::TRIANGLE_STRIP, 0, 4);
        }
    }

    fn draw_circle(&mut self, cx: f32, cy: f32, radius: f32, color: u32) {
        let mut col = unpack_color(color);
        col[3] *= self.global_alpha;
        unsafe {
            self.gl.use_program(Some(self.shape_program));
            self.gl.bind_vertex_array(Some(self.quad_vertex_array));

            let loc_res = self
                .gl
                .get_uniform_location(self.shape_program, "u_resolution");
            let loc_rect_pos = self
                .gl
                .get_uniform_location(self.shape_program, "u_rect_pos");
            let loc_rect_size = self
                .gl
                .get_uniform_location(self.shape_program, "u_rect_size");
            let loc_color = self.gl.get_uniform_location(self.shape_program, "u_color");
            let loc_radius = self.gl.get_uniform_location(self.shape_program, "u_radius");
            let loc_is_circle = self
                .gl
                .get_uniform_location(self.shape_program, "u_is_circle");
            let loc_is_shadow = self
                .gl
                .get_uniform_location(self.shape_program, "u_is_shadow");
            let loc_shape_size = self
                .gl
                .get_uniform_location(self.shape_program, "u_shape_size");

            let rect = Rect {
                x: cx - radius,
                y: cy - radius,
                width: radius * 2.0,
                height: radius * 2.0,
            };

            self.gl
                .uniform_2_f32(loc_res.as_ref(), self.resolution.0, self.resolution.1);
            self.gl.uniform_2_f32(loc_rect_pos.as_ref(), rect.x, rect.y);
            self.gl
                .uniform_2_f32(loc_rect_size.as_ref(), rect.width, rect.height);
            self.gl
                .uniform_2_f32(loc_shape_size.as_ref(), rect.width, rect.height);
            self.gl
                .uniform_4_f32(loc_color.as_ref(), col[0], col[1], col[2], col[3]);
            self.gl.uniform_1_f32(loc_radius.as_ref(), radius);
            self.gl.uniform_1_f32(loc_is_circle.as_ref(), 1.0);
            self.gl.uniform_1_f32(loc_is_shadow.as_ref(), 0.0);

            let loc_transform = self
                .gl
                .get_uniform_location(self.shape_program, "u_transform");
            let t = self.transform_stack.last().unwrap();
            self.gl
                .uniform_matrix_3_f32_slice(loc_transform.as_ref(), false, t);
            self.gl.draw_arrays(glow::TRIANGLE_STRIP, 0, 4);
        }
    }

    #[allow(clippy::too_many_lines)]
    fn draw_text(&mut self, text: &str, x: f32, y: f32, size: f32, color: u32) {
        let mut col = unpack_color(color);
        col[3] *= self.global_alpha;
        unsafe {
            self.gl.use_program(Some(self.text_program));
            self.gl.bind_vertex_array(Some(self.quad_vertex_array));
            self.gl.active_texture(glow::TEXTURE0);
            self.gl
                .bind_texture(glow::TEXTURE_2D, Some(self.font_texture));

            let loc_res = self
                .gl
                .get_uniform_location(self.text_program, "u_resolution");
            let loc_rect_pos = self
                .gl
                .get_uniform_location(self.text_program, "u_rect_pos");
            let loc_rect_size = self
                .gl
                .get_uniform_location(self.text_program, "u_rect_size");
            let loc_color = self.gl.get_uniform_location(self.text_program, "u_color");
            let loc_uv_start = self
                .gl
                .get_uniform_location(self.text_program, "u_uv_start");
            let loc_uv_end = self.gl.get_uniform_location(self.text_program, "u_uv_end");

            self.gl
                .uniform_2_f32(loc_res.as_ref(), self.resolution.0, self.resolution.1);
            self.gl
                .uniform_4_f32(loc_color.as_ref(), col[0], col[1], col[2], col[3]);

            if let Some(ref atlas) = self.font_atlas {
                let scale = size / atlas.rasterize_size;
                let mut curr_x = x;
                // baseline_y: top of text box + ascent (pixels from top to baseline)
                let baseline_y = atlas.ascent.mul_add(scale, y);

                let aw =
                    f32::from(u16::try_from(self.atlas_width).expect("atlas width fits in u16"));
                let ah =
                    f32::from(u16::try_from(self.atlas_height).expect("atlas height fits in u16"));

                for c in text.chars() {
                    if c == ' ' {
                        curr_x = atlas.space_advance.mul_add(scale, curr_x);
                        continue;
                    }

                    let glyph = atlas
                        .glyphs
                        .get(&c)
                        .unwrap_or_else(|| atlas.glyphs.get(&'?').unwrap());
                    if glyph.width == 0 || glyph.height == 0 {
                        curr_x = glyph.advance_width.mul_add(scale, curr_x);
                        continue;
                    }

                    let gw =
                        f32::from(u16::try_from(glyph.width).expect("glyph width fits in u16"))
                            * scale;
                    let gh =
                        f32::from(u16::try_from(glyph.height).expect("glyph height fits in u16"))
                            * scale;

                    // bearing_y = distance from baseline to TOP of glyph (positive = above)
                    // So the top-left corner of the quad is at baseline_y - bearing_y*scale
                    let draw_x = glyph.bearing_x.mul_add(scale, curr_x);
                    let draw_y = glyph.bearing_y.mul_add(-scale, baseline_y);

                    // UV coordinates in [0,1] space within atlas texture
                    let u_min_x =
                        f32::from(u16::try_from(glyph.atlas_x).expect("atlas x fits in u16")) / aw;
                    let u_min_y =
                        f32::from(u16::try_from(glyph.atlas_y).expect("atlas y fits in u16")) / ah;
                    let u_max_x = f32::from(
                        u16::try_from(glyph.atlas_x + glyph.width).expect("atlas x fits in u16"),
                    ) / aw;
                    let u_max_y = f32::from(
                        u16::try_from(glyph.atlas_y + glyph.height).expect("atlas y fits in u16"),
                    ) / ah;

                    self.gl.uniform_2_f32(loc_rect_pos.as_ref(), draw_x, draw_y);
                    self.gl.uniform_2_f32(loc_rect_size.as_ref(), gw, gh);
                    self.gl
                        .uniform_2_f32(loc_uv_start.as_ref(), u_min_x, u_min_y);
                    self.gl.uniform_2_f32(loc_uv_end.as_ref(), u_max_x, u_max_y);

                    let loc_transform = self
                        .gl
                        .get_uniform_location(self.text_program, "u_transform");
                    let t = self.transform_stack.last().unwrap();
                    self.gl
                        .uniform_matrix_3_f32_slice(loc_transform.as_ref(), false, t);
                    self.gl.draw_arrays(glow::TRIANGLE_STRIP, 0, 4);
                    curr_x = glyph.advance_width.mul_add(scale, curr_x);
                }
            } else {
                let char_width = size;
                let char_height = size;
                let gap = size * 0.1;

                let mut curr_x = x;
                for c in text.chars() {
                    let ascii_code = c as u32;
                    let idx = if (32..=127).contains(&ascii_code) {
                        f32::from(u16::try_from(ascii_code - 32).expect("ASCII index fits in u16"))
                    } else {
                        95.0
                    };

                    self.gl.uniform_2_f32(loc_rect_pos.as_ref(), curr_x, y);
                    self.gl
                        .uniform_2_f32(loc_rect_size.as_ref(), char_width, char_height);
                    self.gl
                        .uniform_2_f32(loc_uv_start.as_ref(), idx / 96.0, 0.0);
                    self.gl
                        .uniform_2_f32(loc_uv_end.as_ref(), (idx + 1.0) / 96.0, 1.0);

                    let loc_transform = self
                        .gl
                        .get_uniform_location(self.text_program, "u_transform");
                    let t = self.transform_stack.last().unwrap();
                    self.gl
                        .uniform_matrix_3_f32_slice(loc_transform.as_ref(), false, t);
                    self.gl.draw_arrays(glow::TRIANGLE_STRIP, 0, 4);
                    curr_x += char_width + gap;
                }
            }
        }
    }

    fn begin_frame(&mut self, width: f32, height: f32) {
        self.resolution = (width, height);
        unsafe {
            self.gl
                .viewport(0, 0, f32_to_i32(width), f32_to_i32(height));
        }
    }

    fn end_frame(&mut self) {
        // Double buffering is handled by windowing wrapper (SDL2 SwapBuffers / EGL SwapBuffers)
    }

    fn set_clip_rect(&mut self, rect: Rect) {
        unsafe {
            self.gl.enable(glow::SCISSOR_TEST);
            let y = self.resolution.1 - rect.y - rect.height;
            self.gl.scissor(
                f32_to_i32(rect.x),
                f32_to_i32(y),
                f32_to_i32(rect.width),
                f32_to_i32(rect.height),
            );
        }
    }

    fn clear_clip_rect(&mut self) {
        unsafe {
            self.gl.disable(glow::SCISSOR_TEST);
        }
    }

    fn push_clip_rect(&mut self, rect: Rect, radius: f32) {
        // Compute intersection with current clip rect
        let current = if let Some(&(cur_rect, _)) = self.clip_stack.last() {
            let cx = cur_rect.x.max(rect.x);
            let cy = cur_rect.y.max(rect.y);
            let cw = (cur_rect.x + cur_rect.width).min(rect.x + rect.width) - cx;
            let ch = (cur_rect.y + cur_rect.height).min(rect.y + rect.height) - cy;
            Rect::new(cx, cy, cw.max(0.0), ch.max(0.0))
        } else {
            rect
        };
        self.clip_stack.push((current, radius));
        self.set_clip_rect(current);
    }

    fn pop_clip_rect(&mut self) {
        self.clip_stack.pop();
        if let Some(&(rect, _)) = self.clip_stack.last() {
            self.set_clip_rect(rect);
        } else {
            self.clear_clip_rect();
        }
    }
    fn push_transform(&mut self, cx: f32, cy: f32, scale: f32, rotate: f32, tx: f32, ty: f32) {
        let p = self
            .transform_stack
            .last()
            .copied()
            .unwrap_or([1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]);

        let rot_rad = rotate.to_radians();
        let c = rot_rad.cos() * scale;
        let s = rot_rad.sin() * scale;

        // Child transform B in OpenGL column-major order:
        // Col 0: [c, s, 0]
        // Col 1: [-s, c, 0]
        // Col 2: [b6, b7, 1]
        let b0 = c;
        let b1 = s;

        let b3 = -s;
        let b4 = c;

        let b6 = cx + tx - (c * cx - s * cy);
        let b7 = cy + ty - (s * cx + c * cy);

        // Column-major Matrix Multiplication: R = P * B
        let res = [
            b1.mul_add(p[3], p[0] * b0),
            b1.mul_add(p[4], p[1] * b0),
            b1.mul_add(p[5], p[2] * b0),

            b4.mul_add(p[3], p[0] * b3),
            b4.mul_add(p[4], p[1] * b3),
            b4.mul_add(p[5], p[2] * b3),

            p[6] + b7.mul_add(p[3], p[0] * b6),
            p[7] + b7.mul_add(p[4], p[1] * b6),
            p[8] + b7.mul_add(p[5], p[2] * b6),
        ];

        self.transform_stack.push(res);
    }

    fn pop_transform(&mut self) {
        if self.transform_stack.len() > 1 {
            self.transform_stack.pop();
        }
    }

    fn set_global_alpha(&mut self, alpha: f32) {
        self.global_alpha = alpha;
    }

    fn load_image(&mut self, id: &str, rgba_pixels: &[u8], width: u32, height: u32) {
        unsafe {
            if !self.image_textures.contains_key(id) {
                let tex = self.gl.create_texture().unwrap();
                self.gl.bind_texture(glow::TEXTURE_2D, Some(tex));
                self.gl.tex_image_2d(
                    glow::TEXTURE_2D,
                    0,
                    i32::try_from(glow::RGBA).expect("RGBA fits in i32"),
                    i32::try_from(width).expect("width fits in i32"),
                    i32::try_from(height).expect("height fits in i32"),
                    0,
                    glow::RGBA,
                    glow::UNSIGNED_BYTE,
                    glow::PixelUnpackData::Slice(Some(rgba_pixels)),
                );
                self.gl.tex_parameter_i32(
                    glow::TEXTURE_2D,
                    glow::TEXTURE_MIN_FILTER,
                    i32::try_from(glow::LINEAR).unwrap(),
                );
                self.gl.tex_parameter_i32(
                    glow::TEXTURE_2D,
                    glow::TEXTURE_MAG_FILTER,
                    i32::try_from(glow::LINEAR).unwrap(),
                );
                self.gl.tex_parameter_i32(
                    glow::TEXTURE_2D,
                    glow::TEXTURE_WRAP_S,
                    i32::try_from(glow::CLAMP_TO_EDGE).unwrap(),
                );
                self.gl.tex_parameter_i32(
                    glow::TEXTURE_2D,
                    glow::TEXTURE_WRAP_T,
                    i32::try_from(glow::CLAMP_TO_EDGE).unwrap(),
                );

                #[allow(clippy::cast_precision_loss)]
                self.image_textures
                    .insert(id.to_string(), (tex, width as f32, height as f32));
            }
        }
    }

    fn has_image(&self, id: &str) -> bool {
        self.image_textures.contains_key(id)
    }

    fn load_wallpaper(&mut self, rgba_pixels: &[u8], width: u32, height: u32) {
        unsafe {
            if let Some((old_tex, _, _)) = self.image_textures.remove("__system_wallpaper__") {
                self.gl.delete_texture(old_tex);
            }
        }
        self.load_image("__system_wallpaper__", rgba_pixels, width, height);
    }

    fn draw_wallpaper(&mut self, width: f32, height: f32) {
        if self.has_image("__system_wallpaper__") {
            let full_rect = Rect::new(0.0, 0.0, width, height);
            self.draw_image(
                "__system_wallpaper__",
                full_rect,
                0.0,
                crate::core::style::ObjectFit::Cover,
            );
            self.draw_rect(
                full_rect,
                0x4000_0000,
                0.0,
                0.0,
                None,
            );
        }
    }

    fn draw_image(
        &mut self,
        id: &str,
        rect: Rect,
        radius: f32,
        object_fit: crate::core::style::ObjectFit,
    ) {
        if let Some(&(tex, img_w, img_h)) = self.image_textures.get(id) {
            let mut draw_rect = rect;
            let mut uv_scale = (1.0_f32, 1.0_f32);
            let mut uv_offset = (0.0_f32, 0.0_f32);

            let img_aspect = img_w / img_h;
            let rect_aspect = rect.width / rect.height;

            match object_fit {
                crate::core::style::ObjectFit::Fill => {}
                crate::core::style::ObjectFit::Contain => {
                    if img_aspect > rect_aspect {
                        let target_h = rect.width / img_aspect;
                        draw_rect.y = rect.y + (rect.height - target_h) / 2.0;
                        draw_rect.height = target_h;
                    } else {
                        let target_w = rect.height * img_aspect;
                        draw_rect.x = rect.x + (rect.width - target_w) / 2.0;
                        draw_rect.width = target_w;
                    }
                }
                crate::core::style::ObjectFit::Cover => {
                    if img_aspect > rect_aspect {
                        let scale_x = rect_aspect / img_aspect;
                        uv_scale.0 = scale_x;
                        uv_offset.0 = (1.0 - scale_x) / 2.0;
                    } else {
                        let scale_y = img_aspect / rect_aspect;
                        uv_scale.1 = scale_y;
                        uv_offset.1 = (1.0 - scale_y) / 2.0;
                    }
                }
            }

            unsafe {
                self.gl.use_program(Some(self.image_program));
                self.gl.bind_vertex_array(Some(self.quad_vertex_array));
                self.gl.active_texture(glow::TEXTURE0);
                self.gl.bind_texture(glow::TEXTURE_2D, Some(tex));

                let loc_res = self
                    .gl
                    .get_uniform_location(self.image_program, "u_resolution");
                let loc_pos = self
                    .gl
                    .get_uniform_location(self.image_program, "u_rect_pos");
                let loc_size = self
                    .gl
                    .get_uniform_location(self.image_program, "u_rect_size");
                let loc_uv_s = self
                    .gl
                    .get_uniform_location(self.image_program, "u_uv_scale");
                let loc_uv_o = self
                    .gl
                    .get_uniform_location(self.image_program, "u_uv_offset");
                let loc_radius = self.gl.get_uniform_location(self.image_program, "u_radius");
                let loc_alpha = self
                    .gl
                    .get_uniform_location(self.image_program, "u_global_alpha");

                self.gl
                    .uniform_2_f32(loc_res.as_ref(), self.resolution.0, self.resolution.1);
                self.gl
                    .uniform_2_f32(loc_pos.as_ref(), draw_rect.x, draw_rect.y);
                self.gl
                    .uniform_2_f32(loc_size.as_ref(), draw_rect.width, draw_rect.height);
                self.gl
                    .uniform_2_f32(loc_uv_s.as_ref(), uv_scale.0, uv_scale.1);
                self.gl
                    .uniform_2_f32(loc_uv_o.as_ref(), uv_offset.0, uv_offset.1);
                self.gl.uniform_1_f32(loc_radius.as_ref(), radius);
                self.gl.uniform_1_f32(loc_alpha.as_ref(), self.global_alpha);

                let loc_transform = self
                    .gl
                    .get_uniform_location(self.image_program, "u_transform");
                let t = self.transform_stack.last().unwrap();
                self.gl
                    .uniform_matrix_3_f32_slice(loc_transform.as_ref(), false, t);
                self.gl.draw_arrays(glow::TRIANGLE_STRIP, 0, 4);
            }
        }
    }

    fn measure_text(&self, text: &str, size: f32) -> f32 {
        self.font_atlas.as_ref().map_or_else(
            || {
                let char_width = size;
                let gap = size * 0.1;
                #[allow(clippy::cast_precision_loss)]
                let count = text.chars().count() as f32;
                if count > 0.0 {
                    (char_width + gap).mul_add(count, -gap)
                } else {
                    0.0
                }
            },
            |atlas| font_atlas::estimate_text_width(atlas, text, size),
        )
    }

    fn text_ascent(&self, size: f32) -> f32 {
        self.font_atlas.as_ref().map_or(
            size * 0.75, // fallback if no atlas
            |atlas| {
                let scale = size / atlas.rasterize_size;
                atlas.ascent * scale
            },
        )
    }
}
